import React from 'react';
import { CheckCircle2 } from 'lucide-react';

const features = [
  "React 18 Architecture",
  "Tailwind CSS Styling", 
  "Framer Motion Animations",
  "Responsive Mobile Design",
  "Clean Architecture Pattern",
  "Domain-Driven Design",
  "Real-time Collaboration",
  "WebSockets Integration",
  "Authentication Ready",
  "Dark/Light Mode Support",
  "SEO Optimized Structure",
  "Accessibility (a11y)",
  "Custom UI Components",
  "Dynamic Routing Support",
  "State Management Setup",
  "API Integration Stubs",
  "Database Schema Models",
  "React Error Boundaries",
  "Loading Skeletons",
  "Toast Notifications",
  "SVG Icons via Lucide",
  "Full Source Code Export",
  "One-click Deployment",
  "Version Control History",
  "Progressive Web App Ready"
];

export default function FeatureShowcase() {
  return (
    <section className="py-24 px-4 sm:px-6 max-w-7xl mx-auto border-t border-white/5">
      <div className="text-center mb-16">
        <h2 className="text-3xl md:text-5xl font-black mb-4">25+ Out-of-the-Box Features</h2>
        <p className="text-gray-400 text-lg">Every app generated by WabiAI comes fully loaded with industry standards.</p>
      </div>
      
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">
        {features.map((feature, i) => (
          <div key={i} className="flex items-center gap-3 p-4 rounded-2xl bg-[#0A0A0A] border border-white/5 hover:border-blue-500/50 hover:bg-white/[0.02] transition-all group hover:shadow-lg hover:shadow-blue-500/5">
            <CheckCircle2 className="w-5 h-5 text-blue-500 group-hover:scale-110 transition-transform shrink-0" />
            <span className="text-sm font-medium text-gray-300 group-hover:text-white transition-colors">{feature}</span>
          </div>
        ))}
      </div>
    </section>
  );
}
